/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // MD3 Color Tokens (Stone/Sage Light Theme)
        'on-secondary-container': '#406c4b',
        'on-error': '#ffffff',
        'on-secondary': '#ffffff',
        'outline': '#7e7570',
        'surface-tint': '#625d5b',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#f9efe8',
        'surface-container-high': '#f0e6e0',
        'on-primary-container': '#888380',
        'secondary': '#3c6847',
        'surface-container-low': '#fcf2eb',
        'on-surface': '#1f1b17',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#ffb4a6',
        'surface-bright': '#fff8f5',
        'surface-container': '#f6ece6',
        'background': '#fff8f5',
        'secondary-fixed-dim': '#a2d2aa',
        'tertiary-container': '#3f0300',
        'on-tertiary-container': '#cb6654',
        'on-tertiary-fixed-variant': '#7d2c1e',
        'surface': '#fff8f5',
        'surface-dim': '#e2d8d2',
        'surface-variant': '#eae1da',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'inverse-primary': '#ccc5c2',
        'secondary-fixed': '#beeec5',
        'tertiary-fixed': '#ffdad4',
        'on-secondary-fixed-variant': '#244f31',
        'on-surface-variant': '#4d4540',
        'on-primary-fixed-variant': '#4a4643',
        'surface-container-highest': '#eae1da',
        'error': '#ba1a1a',
        'on-tertiary-fixed': '#3f0300',
        'on-secondary-fixed': '#00210c',
        'on-error-container': '#93000a',
        'outline-variant': '#d0c4be',
        'on-primary-fixed': '#1e1b19',
        'primary': '#000000',
        'primary-fixed-dim': '#ccc5c2',
        'primary-container': '#1e1b19',
        'secondary-container': '#bbecc2',
        'inverse-surface': '#342f2b',
        'primary-fixed': '#e9e1dd',
        'on-background': '#1f1b17',
        'tertiary': '#000000',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'gutter': '1.5rem',
        'space-md': '1rem',
        'gutter-mobile': '0.75rem',
        'space-xs': '0.25rem',
        'space-xl': '2.5rem',
        'space-lg': '1.5rem',
        'margin-mobile': '1rem',
        'margin': '3rem',
        'space-sm': '0.5rem',
      },
      fontFamily: {
        'headline-lg-mobile': ['Inter'],
        'display': ['Inter'],
        'label-md': ['JetBrains Mono'],
        'headline-sm': ['Inter'],
        'headline-lg': ['Inter'],
        'body-sm': ['Inter'],
        'display-mobile': ['Inter'],
        'label-sm': ['JetBrains Mono'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'headline-md': ['Inter'],
      },
      fontSize: {
        'headline-lg-mobile': ['22px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'display': ['40px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'display-mobile': ['30px', { lineHeight: '36px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
